### ISSUE TITLE
Misleading error message on malformed JSON

### ISSUE THREAD

**Issue by arnecls** [msiebeneicher/chapi#38]
I had a job file with a missing "{" at the beginning.
The error message I got was
```
Argument 1 passed to "Chapi\Entity\Chronos\JobEntity::__construct" must be an array or object
```
It would be nice if this could be more descriptive and, if possible, point to the file/line producing the error.

**Comment by msiebeneicher** [comment]
This pull request should fix the issue with invalid json files: https://github.com/msiebeneicher/chapi/pull/40
